# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/sergey/Рабочий стол/work/oop_exercise_08"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/sergey/Рабочий стол/work/oop_exercise_08"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sergey/Рабочий стол/work/oop_exercise_08/CMakeFiles" "/home/sergey/Рабочий стол/work/oop_exercise_08/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sergey/Рабочий стол/work/oop_exercise_08/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oop_exercise_08

# Build rule for target.
oop_exercise_08: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oop_exercise_08
.PHONY : oop_exercise_08

# fast build rule for target.
oop_exercise_08/fast:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/build
.PHONY : oop_exercise_08/fast

Figure.o: Figure.cpp.o

.PHONY : Figure.o

# target to build an object file
Figure.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Figure.cpp.o
.PHONY : Figure.cpp.o

Figure.i: Figure.cpp.i

.PHONY : Figure.i

# target to preprocess a source file
Figure.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Figure.cpp.i
.PHONY : Figure.cpp.i

Figure.s: Figure.cpp.s

.PHONY : Figure.s

# target to generate assembly for a file
Figure.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Figure.cpp.s
.PHONY : Figure.cpp.s

Point.o: Point.cpp.o

.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i

.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s

.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Point.cpp.s
.PHONY : Point.cpp.s

Rectangle.o: Rectangle.cpp.o

.PHONY : Rectangle.o

# target to build an object file
Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rectangle.cpp.o
.PHONY : Rectangle.cpp.o

Rectangle.i: Rectangle.cpp.i

.PHONY : Rectangle.i

# target to preprocess a source file
Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rectangle.cpp.i
.PHONY : Rectangle.cpp.i

Rectangle.s: Rectangle.cpp.s

.PHONY : Rectangle.s

# target to generate assembly for a file
Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rectangle.cpp.s
.PHONY : Rectangle.cpp.s

Rhombus.o: Rhombus.cpp.o

.PHONY : Rhombus.o

# target to build an object file
Rhombus.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rhombus.cpp.o
.PHONY : Rhombus.cpp.o

Rhombus.i: Rhombus.cpp.i

.PHONY : Rhombus.i

# target to preprocess a source file
Rhombus.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rhombus.cpp.i
.PHONY : Rhombus.cpp.i

Rhombus.s: Rhombus.cpp.s

.PHONY : Rhombus.s

# target to generate assembly for a file
Rhombus.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Rhombus.cpp.s
.PHONY : Rhombus.cpp.s

Subscriber.o: Subscriber.cpp.o

.PHONY : Subscriber.o

# target to build an object file
Subscriber.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Subscriber.cpp.o
.PHONY : Subscriber.cpp.o

Subscriber.i: Subscriber.cpp.i

.PHONY : Subscriber.i

# target to preprocess a source file
Subscriber.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Subscriber.cpp.i
.PHONY : Subscriber.cpp.i

Subscriber.s: Subscriber.cpp.s

.PHONY : Subscriber.s

# target to generate assembly for a file
Subscriber.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Subscriber.cpp.s
.PHONY : Subscriber.cpp.s

Trapeze.o: Trapeze.cpp.o

.PHONY : Trapeze.o

# target to build an object file
Trapeze.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Trapeze.cpp.o
.PHONY : Trapeze.cpp.o

Trapeze.i: Trapeze.cpp.i

.PHONY : Trapeze.i

# target to preprocess a source file
Trapeze.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Trapeze.cpp.i
.PHONY : Trapeze.cpp.i

Trapeze.s: Trapeze.cpp.s

.PHONY : Trapeze.s

# target to generate assembly for a file
Trapeze.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/Trapeze.cpp.s
.PHONY : Trapeze.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/oop_exercise_08.dir/build.make CMakeFiles/oop_exercise_08.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... oop_exercise_08"
	@echo "... edit_cache"
	@echo "... Figure.o"
	@echo "... Figure.i"
	@echo "... Figure.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... Rectangle.o"
	@echo "... Rectangle.i"
	@echo "... Rectangle.s"
	@echo "... Rhombus.o"
	@echo "... Rhombus.i"
	@echo "... Rhombus.s"
	@echo "... Subscriber.o"
	@echo "... Subscriber.i"
	@echo "... Subscriber.s"
	@echo "... Trapeze.o"
	@echo "... Trapeze.i"
	@echo "... Trapeze.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

